# Generated by Django 5.0.3 on 2024-05-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chinatubshower',
            name='id',
        ),
        migrations.RemoveField(
            model_name='delta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='moen',
            name='id',
        ),
        migrations.AlterField(
            model_name='chinatubshower',
            name='model_number',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='delta',
            name='model_number',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moen',
            name='model_number',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
