# Generated by Django 5.0.3 on 2024-05-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_chinatubshower_id_remove_delta_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinatubshower',
            name='baker_mitchell',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chinatubshower',
            name='cregger',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chinatubshower',
            name='ferguson',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chinatubshower',
            name='gateway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chinatubshower',
            name='hubbard',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chinatubshower',
            name='hughes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delta',
            name='collection',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moen',
            name='collection',
            field=models.CharField(blank=True, null=True),
        ),
    ]
