# Generated by Django 5.0.3 on 2024-05-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_chinatubshower_baker_mitchell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinatubshower',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
