# Generated by Django 5.0.3 on 2024-05-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chinatubshower_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('model_number', models.CharField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='builder',
            name='base_house_color',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='base_lav_faucet',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='base_shower_trim',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='base_trap_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='base_ts_trim',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='closet',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='closet_seat',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='fixt_brand',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='garbage_disposal',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='kitchen_faucet',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='markup',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='pedestal_lav',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='sewer_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='water_heater',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='builder',
            name='water_line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
