# Generated by Django 5.0.3 on 2024-05-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_misc_alter_builder_base_house_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField()),
                ('description', models.CharField(blank=True, null=True)),
                ('price', models.FloatField()),
            ],
        ),
    ]
