# Generated by Django 5.0.3 on 2024-05-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_labor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='price',
            field=models.IntegerField(),
        ),
    ]
