# Generated by Django 5.0.3 on 2024-05-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_labor_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChinaTubShower',
            new_name='ChinaParts',
        ),
        migrations.AddField(
            model_name='misc',
            name='category',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='misc',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='misc',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
