# Generated by Django 5.0.3 on 2024-05-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_chinatubshower_chinaparts_misc_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinaparts',
            name='collection',
            field=models.CharField(blank=True, null=True),
        ),
    ]
