# Generated by Django 5.0.3 on 2024-07-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_misc_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builder',
            old_name='base_lav_faucet',
            new_name='base_pri_lav_faucet',
        ),
        migrations.AddField(
            model_name='builder',
            name='base_sec_lav_faucet',
            field=models.CharField(blank=True, null=True),
        ),
    ]
