# Generated by Django 5.0.3 on 2024-07-08 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_base_lav_faucet_builder_base_pri_lav_faucet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=50, null=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.builder')),
            ],
        ),
    ]
